### ISSUE TITLE
Not sure on login details 

### ISSUE THREAD

**Issue by batessam** [rchrch/homebridge-mhacwifi1-lan#10]
Hi I’m not sure if this is the best place to ask a question but I can’t seem to get this plugin to work, I have access to the AC unit via the Smart M-Air app at the moment is this the user and and password I need to enter into the config?

**Comment by rchrch** [comment]
The plugin works with local control to the aircon (not via an external/cloud based application).  The default username is "admin" and the default password is "admin" as well.  Unless you have changed those via the aircon's local web page, I would expect those values to work.

**Comment by woodgieboodgie** [comment]
Hi,

Receiving an error from the plugin despite the air conditioners being online.  I have not changed the username and password, and have left it as default admin, admin.

Http request error: Error: connect ECONNREFUSED 192.168.0.162:80
[29/05/2023, 5:52:42 pm] [Bedroom 2 AC] No device found at address: 192.168.0.162 (Error: connect ECONNREFUSED 192.168.0.162:80)

**Comment by batessam** [comment]
Yep that’s the same issue I am getting, if I try going to the IP in chrome I see no webpage like was suggested in the comments above

**Comment by woodgieboodgie** [comment]
I have 4 units, 3 give no webpage, 1 does.. yet all 4 respond to ip pings. have you tried a power cycle at the condenser?

**Comment by rchrch** [comment]
Couple things to check:

1. Is your AC a Mitsubishi Heavy Industries split system?
2. Is the installed wifi adaptor a MH-AC-WIFI-1 model?
3. Have you verified the IP address you're using is the one assigned by your router (or dhcp server) to the split?   Your router should hopefully tell you what IPs are assigned to the MACs on your network.  The first three bytes of a MAC address indicate the vendor.  My split systems all start with CE:3F:1D.  I'd imaging all MH-AC-WIFI-1 devices have this same prefix.
4. I haven't used the Smart M-air app.  I initially used the Intesis AC Cloud app (https://apps.apple.com/au/app/intesis-ac-cloud/id500095280) before writing the homebridge plugin as it was the one the wifi adapter installation instructions referred to.  Home assistant forums talk about a WF-RAC model associated with the Smart M-air.  Is it possible this is the wifi module you are using?

Here's a screen shot of the Intesis MH-AC-WIFI-1's local webpage:
![intesis-web-page](https://github.com/rchrch/homebridge-mhacwifi1-lan/assets/10507828/fac6a674-4c91-416b-8a9b-d7a71d0c023d)

**Comment by woodgieboodgie** [comment]
MACs are tied to fixed IP addresses provided from the router. DHCP gave the initial addresses...  thereafter they were fixed.  The AC's are Mitsubishi Heavy Industries split system, the card is a MH-AC-WIFI-1, same CE:3F:1D prefix.  Got to the screen you posted above on one of the four (via Chromium on a Pi) but then it dropped away as well. Can get to the units via the Intensis app.  Could be browser related i suppose? be great to remotely re-initialise the wifi card.

**Comment by rchrch** [comment]
How far away from the wifi are the splits?  If you can get back to the Intesis web page you should see “Wireless Signal Strength”.  Ideally that should be between -50 and -60 dBm.  If the value is above -60, the wifi flakes out quite often.  Sometimes the router’s web management page will show this information as well.  I needed an access-point placed closer to a couple of the splits in my house.

Also, f you comfortable with command line, try running `curl -v http://the-ip-address <http://the-ip-address/> | gzip -d` from your Pi.  That will make a web requested from the command line.  If this isn’t working there is either an IP assignment problem or wifi connectivity problem.

I think the only way to reset the card would be to switch off power to the split  Just to double check, can you verify the IP addresses on your router?  DHCP assigns addresses, but that doesn’t mean they won’t change from time to time.

**Comment by woodgieboodgie** [comment]
i type in `curl -v http://the-ip-address <http://the-ip-address/> | gzip -d` and get an error.  is that syntax correct?
MHI have stated there was an update to the wifi units software and to power off the units at the condenser for 5 mins, and then wait up to 10mins for each controller to update.

**Comment by woodgieboodgie** [comment]
![script run](https://github.com/rchrch/homebridge-mhacwifi1-lan/assets/52473319/ed7e7baa-075a-486b-8cab-8b45fdd40be0)

**Comment by rchrch** [comment]
You command is correct.  The connection refused means the 192.168.0.162 address isn't accepting the HTTP connection.  If the aircon wifi is truly assigned to 192.168.0.162, it is not responding.  Definitely try power cycling.  You should verify the IP address assigned to it on the router after it is cycled to make sure it isn't reassigned.  If you haven't already, you should make the IP assigned to the split "fixed" to that address so it will always be assigned that IP when the DHCP lease expires.

**Comment by woodgieboodgie** [comment]
The IPs are already fixed, their MACs match the IPs being given.  Now the tech from Intesis states their v2 wifi adapter (the ones that start with CC3F was only available for older devices??) Yet I definitely saw the webpage on one of my four units before it disappeared, and your MAC prefix is the same as mine.  Here is what he sent me:

![from intesis](https://github.com/rchrch/homebridge-mhacwifi1-lan/assets/52473319/0eb3b5bd-42cb-4980-a2fd-96470540b563)

Sounds to me like a flaky web server built into these units.

**Comment by woodgieboodgie** [comment]
Do you have any other suggestions?  Does the advice from the manufacturer resonate as I was of the belief you have the plugin talking to the latter models of the wifi adapter from Intensis
________________________________

**Comment by sambatesdesign** [comment]
still get "[23/10/2023, 16:29:35] [Office Aircon] Http request error: Error: connect ECONNREFUSED 192.168.1.116:80
[23/10/2023, 16:29:35] [Office Aircon] No device found at address: 192.168.1.116 (Error: connect ECONNREFUSED 192.168.1.116:80)"

the mac address for the device seems to be ec:0b:ae:b9:22:7b i wonder if MH have updated the wifi cards they use? its a new system install from about 3 months ago

**Comment by wdotcx** [comment]
Had a second Mitsubishi A/C installed last week, no web interface on the new MH-AC-WIFI-1 unit, whereas my existing Mitsubishi A/C has a web interface. Did some digging and found the web interface is only available on the discontinued model with part number INWFIMHI001I000 (https://www.intesis.com/support/discontinued-products#INWFIMHI001I000).

The current model with part number INWFIMHI001I100 (https://www.intesis.com/products/cloud-solutions/ac-cloud-control/mitsubishi-heavy-accc-wifi-ac-mh-ac-wfi-1?ordercode=INWFIMHI001I100) doesn't have a web interface.

**Comment by CameronVIE** [comment]
The port where the unit answers is

51443

**Comment by sambatesdesign** [comment]
![Screenshot 2024-05-08 at 12 30 36 pm](https://github.com/rchrch/homebridge-mhacwifi1-lan/assets/30127726/c3dc4616-fe7c-436f-aa2d-744bced081a6)
yer if i use that port number i get this message in chrome, if i add that port number in the config i still get device not found error from the plugin =(

**Comment by CameronVIE** [comment]
Here is a very useful and progressive communitywork on an plugin for homeassistant - they made it to work!

https://community.home-assistant.io/t/mitsubishi-wifi-module-wf-rac-smart-m-air/411025/136?page=2

**Comment by rchrch** [comment]
There's a lot going on in the thread and seems focused on the smart-m-air solution which is different that the one this plugin supports.  If you have additional details, I'm happy to try and help, but it looks like this is related to something else.
